apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonapp-deployment
  labels:
    app: pythonapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pythonapp
  template:
    metadata:
      labels:
        app: pythonapp
    spec:
      containers:
      - name: pythonapp
        image: pygoat/pygoat
        ports:
        - containerPort: 8000
        env: 
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
               name: postgres-secret
               key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: postgres-url

---
apiVersion: v1
kind: Service
metadata:
  name: pythonapp-service
spec:
  type: NodePort
  selector:
    app: pythonapp
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30100
